version: '3.7'
services:
    app:
        container_name: artificilalwebsite
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true